### PR TITLE
`xev.Dynamic` to choose between multiple backends at runtime

### LINKED ISSUE #131: Automatic fallback to `Epoll` if `io_uring` is not available
This should be a discussion, but I can't figure out how to make one.

It would be nice if `libxev` automatically tried the `Epoll` backend on Linux if the call to `io_uring_setup()` fails.

A real-life scenario where `io_uring` might not be available but `Epoll` might be is if the `kernel.io_uring_disabled` sysctl was disabled, which would result in `io_uring_setup()` setting `errno` to `EPERM` (as far as I can tell, the Zig wrapper does not translate this to an error union).  I don't know of any distribution which does this by default other than Arch Linux if you use the hardened kernel.

A possible downside (and the main reason why this should be a discussion) is that both `io_uring` and `Epoll` backends are compiled into the binary even if only one is used, which is antithetical to the point "Tree Shaking" mentioned in the `README`.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #131 

This introduces a new `xev.Dynamic` that mimics the `xev.IO_Uring`, `xev.Epoll`, etc. APIs but chooses an available API at runtime (and also supports manually setting the backend at runtime). There is also a new `xev.DynamicXev()` function that can be used at comptime to create different backend fallbacks. 

The API is identical to `xev` (top-level), `xev.Epoll`, etc. To use it, callers just need to replace their import:

```zig
// From:
const xev = @import("xev");

// To:
const xev = @import("xev").Dynamic;
```

Callers should also call `detect` early in their program before anything runs:

```
try xev.detect();
```

Or they can manually set it:

```
xev.backend = .epoll;
```

Given the runtime dispatch, there is a small performance hit, but given the benchmarks, its negligible: 

```
## Static

info: async1: 3.85 seconds (25974.39/sec)
info: async2: 3.77 seconds (26543.82/sec)
info: async4: 3.59 seconds (27837.56/sec)
info: async8: 3.52 seconds (28437.08/sec)
info: async_pummel_1: 1000000 callbacks in 0.31 seconds (3237817.20/sec)
info: async_pummel_2: 1000000 callbacks in 0.46 seconds (2157493.11/sec)
info: async_pummel_4: 1000000 callbacks in 0.83 seconds (1211627.05/sec)
info: async_pummel_8: 1000000 callbacks in 1.43 seconds (698269.07/sec)

timers:
info: 10.00 seconds total
info: 0.23 seconds init
info: 9.77 seconds dispatch
info: 0.00 seconds cleanup

Ping-pongs:
info: 27631.21 roundtrips/s
info: 18.10 seconds total

info: ping_pongs: 1 pingers, ~716888 roundtrips/s
info: udp_pummel_1v1: 708041f/s received, 708040f/s sent, 1000001 received, 1000000 sent in 1.4 seconds

## Dynamic

info: async1: 3.73 seconds (26788.04/sec)
info: async1: 3.84 seconds (26033.06/sec)
info: async2: 3.80 seconds (26317.92/sec)
info: async2: 3.82 seconds (26152.52/sec)
info: async4: 3.77 seconds (26507.44/sec)
info: async8: 3.66 seconds (27327.84/sec)

info: async_pummel_1: 1000000 callbacks in 0.32 seconds (3167606.15/sec)
info: async_pummel_2: 1000000 callbacks in 0.41 seconds (2435983.01/sec)
info: async_pummel_4: 1000000 callbacks in 0.52 seconds (1929071.52/sec)
info: async_pummel_8: 1000000 callbacks in 0.85 seconds (1179432.21/sec)

Timer:
info: 10.00 seconds total
info: 0.49 seconds init
info: 9.51 seconds dispatch
info: 0.00 seconds cleanup

Ping-pongs:
info: 26716.33 roundtrips/s
info: 18.72 seconds total

info: ping_pongs: 1 pingers, ~717047 roundtrips/s
info: udp_pummel_1v1: 725060f/s received, 725059f/s sent, 1000001 received, 1000000 sent in 1.4 seconds
```

### CODE REVIEW

File: src/backend/io_uring.zig [hunk 1]
```diff
@@ -1,10 +1,29 @@
...
+const builtin = @import("builtin");
 const assert = std.debug.assert;
 const linux = std.os.linux;
 const posix = std.posix;
 const queue = @import("../queue.zig");
 const xev = @import("../main.zig").IO_Uring;
 
+/// True if this backend is available on this platform.
+pub fn available() bool {
+    if (comptime builtin.os.tag != .linux) return true;
```
Comment (unexge) [inline src/backend/io_uring.zig:11]: Shouldn't this return false? Though probably doesn't matter as `Backend.candidates()` only returns this on Linux
